<?php

namespace Gestion\PaiementBundle\Repository;

/**
 * PaiementEnseignantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementEnseignantRepository extends \Doctrine\ORM\EntityRepository
{
}
