<?php

namespace Gestion\PaiementBundle\Repository;

/**
 * PaiementEtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementEtudiantRepository extends \Doctrine\ORM\EntityRepository
{
}
