<?php

namespace Admin\AdminBundle\Repository;

/**
 * DroitAccesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DroitAccesRepository extends \Doctrine\ORM\EntityRepository
{
}
