<?php

namespace Admin\AdminBundle\Repository;

/**
 * LiaisonDroitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiaisonDroitRepository extends \Doctrine\ORM\EntityRepository
{
}
