gestion_entreprise:
    resource: "@GestionEntrepriseBundle/Resources/config/routing.yml"
    prefix:   /

gestion_note:
    resource: "@GestionNoteBundle/Resources/config/routing.yml"
    prefix:   /

gestion_event:
    resource: "@GestionEventBundle/Resources/config/routing.yml"
    prefix:   /

gestion_absence:
    resource: "@GestionAbsenceBundle/Resources/config/routing.yml"
    prefix:   /

gestion_ue:
    resource: "@GestionUEBundle/Resources/config/routing.yml"
    prefix:   /

gestion_enseignant:
    resource: "@GestionEnseignantBundle/Resources/config/routing.yml"
    prefix:   /

gestion_niveau:
    resource: "@GestionNiveauBundle/Resources/config/routing.yml"
    prefix:   /

gestion_filiere:
    resource: "@GestionFiliereBundle/Resources/config/routing.yml"
    prefix:   /

gestion_salle:
    resource: "@GestionSalleBundle/Resources/config/routing.yml"
    prefix:   /

gestion_preinscription:
    resource: "@GestionPreinscriptionBundle/Resources/config/routing.yml"
    prefix:   /

matiere_gestion_matiere:
    resource: "@GestionMatiereBundle/Resources/config/routing.yml"
    prefix:   /

admin_admin:
    resource: "@AdminAdminBundle/Resources/config/routing.yml"
    prefix:   /

user_user:
    resource: "@UserUserBundle/Resources/config/routing.yml"
    prefix:   /

er_pviescolaire:
    resource: "@ERPviescolaireBundle/Resources/config/routing.yml"
    prefix:   /

er_pvuescolaire:
    resource: "@ERPvuescolaireBundle/Resources/config/routing.yml"
    prefix:   /

erp_etudiant:
    resource: "@ERPEtudiantBundle/Resources/config/routing.yml"
    prefix:   /

erp_parent:
    resource: "@ERPParentBundle/Resources/config/routing.yml"
    prefix:   /

erp_enseignant:
    resource: "@ERPEnseignantBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

profile_route:
    path: /profile
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fos_user_profile_edit
        permanent: true

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

