gestion_salle:
    resource: "@GestionSalleBundle/Resources/config/routing.yml"
    prefix:   /

gestion_enseignant:
    resource: "@GestionEnseignantBundle/Resources/config/routing.yml"
    prefix:   /

gestion_absence:
    resource: "@GestionAbsenceBundle/Resources/config/routing.yml"
    prefix:   /

gestion_niveau:
    resource: "@GestionNiveauBundle/Resources/config/routing.yml"
    prefix:   /

gestion_filiere:
    resource: "@GestionFiliereBundle/Resources/config/routing.yml"
    prefix:   /

gestion_ue:
    resource: "@GestionUEBundle/Resources/config/routing.yml"
    prefix:   /

gestion_matiere:
    resource: "@GestionMatiereBundle/Resources/config/routing.yml"
    prefix:   /

gestion_preinscription:
    resource: "@GestionPreinscriptionBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


