# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    twig.extension.sortbyfield:
        class: Snilius\Twig\SortByFieldExtension
        tags:
            - { name: twig.extension }
    redirect.after.login:
        class: User\UserBundle\Redirection\AfterLoginRedirection
        arguments: ["@router"]
    redirect.after.logout:
        class: User\UserBundle\Redirection\AfterLogoutRedirection
        arguments: ["@router", "@security.token_storage"]