gestion_ue_homepage:
    path:     /Unite_Enseignement
    defaults: { _controller: GestionUEBundle:Default:index }

Liste_UE:
    path:     /Unite_Enseignement/liste
    defaults: { _controller: GestionUEBundle:Default:list }

AjoutUnites:
    path:     /Unite_Enseignement/new
    defaults: { _controller: GestionUEBundle:Default:AjouterUE }

modifierUE:
    path: /Unite_Enseignement/modifier/{id}
    defaults: { _controller: GestionUEBundle:Default:modifierUE }

supprimerUE:
    path: /Unite_Enseignement/supprimer/{id}
    defaults: { _controller: GestionUEBundle:Default:supprimerUE }

filieres_list_ajax_call:
    path:     /ajax/filieres_list
    defaults: { _controller: GestionUEBundle:Default:ajaxGetFilieres }

Save_Query_Unites:
    path:     /Unite_Enseignement/ajouterUE
    defaults: { _controller: GestionUEBundle:Default:Save_Query }