<?php

namespace Gestion\PreinscriptionBundle\Repository;

/**
 * EtudiantRechercheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantRechercheRepository extends \Doctrine\ORM\EntityRepository
{
}
