<?php

namespace Gestion\PreinscriptionBundle\Repository;

/**
 * preinscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class preinscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
