<?php

namespace Gestion\PreinscriptionBundle\Repository;

/**
 * PreinscritRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreinscritRepository extends \Doctrine\ORM\EntityRepository
{
}
