listMatiere:
    path:     /matieres/liste
    defaults: { _controller: GestionMatiereBundle:Default:listMatiere }

AjoutMatiere:
    path:     /matieres/ajouter
    defaults: { _controller: GestionMatiereBundle:Default:AjoutMatiere }

modifierMatiere:
    path:     /matieres/edit/{id}
    defaults: { _controller: GestionMatiereBundle:Default:modifierMatiere }

deleteMatiere:
    path:     /matieres/delete/{id}
    defaults: { _controller: GestionMatiereBundle:Default:deleteMatiere }

