gestion_admin_homepage:
    path:     /
    defaults: { _controller: GestionAdminBundle:Default:index }

dashbord2:
    path:     /dashbord2
    defaults: { _controller: GestionAdminBundle:Default:dashbord2 }
dashbord3:
    path:     /dashbord3
    defaults: { _controller: GestionAdminBundle:Default:dashbord3 }
ui_colors:
    path:     /ui_colors
    defaults: { _controller: GestionAdminBundle:Default:ui_colors }
ui_metronic_grid:
    path:     /ui_metronic_grid
    defaults: { _controller: GestionAdminBundle:Default:ui_metronic_grid }
ui_general:
    path:     /ui_general
    defaults: { _controller: GestionAdminBundle:Default:ui_general }
ui_buttons:
    path:     /ui_buttons
    defaults: { _controller: GestionAdminBundle:Default:ui_buttons }
ui_buttons_spinner:
    path:     /ui_buttons_spinner
    defaults: { _controller: GestionAdminBundle:Default:ui_buttons_spinner }
ui_confirmations:
        path:     /ui_confirmations
        defaults: { _controller: GestionAdminBundle:Default:ui_confirmations }
ui_sweetalert:
        path:     /ui_sweetalert
        defaults: { _controller: GestionAdminBundle:Default:ui_sweetalert }
ui_icons:
        path:     /ui_icons
        defaults: { _controller: GestionAdminBundle:Default:ui_icons }
ui_socicons:
        path:     /ui_socicons
        defaults: { _controller: GestionAdminBundle:Default:ui_socicons }
ui_typography:
        path:     /ui_typography
        defaults: { _controller: GestionAdminBundle:Default:ui_typography }
ui_tabs_accordions_navs:
        path:     /ui_tabs_accordions_navs
        defaults: { _controller: GestionAdminBundle:Default:ui_tabs_accordions_navs }
components_date_time_pickers:
        path:     /components_date_time_pickers
        defaults: { _controller: GestionAdminBundle:Default:components_date_time_pickers }
components_color_pickers:
        path:     /components_color_pickers
        defaults: { _controller: GestionAdminBundle:Default:components_color_pickers }
components_select2:
        path:     /components_select2
        defaults: { _controller: GestionAdminBundle:Default:components_select2 }
components_bootstrap_multiselect_dropdown:
        path:     /components_bootstrap_multiselect_dropdown
        defaults: { _controller: GestionAdminBundle:Default:components_bootstrap_multiselect_dropdown }
components_bootstrap_select:
        path:     /components_bootstrap_select
        defaults: { _controller: GestionAdminBundle:Default:components_bootstrap_select }
components_multi_select:
        path:     /components_multi_select
        defaults: { _controller: GestionAdminBundle:Default:components_multi_select }
components_bootstrap_select_splitter:
        path:     /components_bootstrap_select_splitter
        defaults: { _controller: GestionAdminBundle:Default:components_bootstrap_select_splitter }
components_clipboard:
        path:     /components_clipboard
        defaults: { _controller: GestionAdminBundle:Default:components_clipboard }
components_typeahead:
        path:     /components_typeahead
        defaults: { _controller: GestionAdminBundle:Default:components_typeahead }
components_bootstrap_switch:
        path:     /components_bootstrap_switch
        defaults: { _controller: GestionAdminBundle:Default:components_bootstrap_switch }
form_controls:
        path:     /form_controls
        defaults: { _controller: GestionAdminBundle:Default:form_controls }
form_validation:
        path:     /form_validation
        defaults: { _controller: GestionAdminBundle:Default:form_validation }
form_validation_states_md:
        path:     /form_validation_states_md
        defaults: { _controller: GestionAdminBundle:Default:form_validation_states_md }
form_validation_md:
        path:     /form_validation_md
        defaults: { _controller: GestionAdminBundle:Default:form_validation_md }
form_layouts:
        path:     /form_layouts
        defaults: { _controller: GestionAdminBundle:Default:form_layouts }
form_repeater:
        path:     /form_repeater
        defaults: { _controller: GestionAdminBundle:Default:form_repeater }
form_input_mask:
        path:     /form_input_mask
        defaults: { _controller: GestionAdminBundle:Default:form_input_mask }
form_editable:
        path:     /form_editable
        defaults: { _controller: GestionAdminBundle:Default:form_editable }
portlet_boxed:
        path:     /portlet_boxed
        defaults: { _controller: GestionAdminBundle:Default:portlet_boxed }
portlet_light:
        path:     /portlet_light
        defaults: { _controller: GestionAdminBundle:Default:portlet_light }
portlet_solid:
        path:     /portlet_solid
        defaults: { _controller: GestionAdminBundle:Default:portlet_solid }
portlet_ajax:
        path:     /portlet_ajax
        defaults: { _controller: GestionAdminBundle:Default:portlet_ajax }
portlet_draggable:
        path:     /portlet_draggable
        defaults: { _controller: GestionAdminBundle:Default:portlet_draggable }
maps_google:
        path:     /maps_google
        defaults: { _controller: GestionAdminBundle:Default:maps_google }



























