<?php

namespace Gestion\AbsenceBundle\Repository;

/**
 * AbsenceRetardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceRetardRepository extends \Doctrine\ORM\EntityRepository
{
}
