<?php

namespace Gestion\AbsenceBundle\Repository;

/**
 * AnneScolaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnneScolaireRepository extends \Doctrine\ORM\EntityRepository
{
}
